baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'about'
pageRef = '/about'
weight = 10

[[menus.main]]
name = 'code'
pageRef = '/code'
weight = 20

[[menus.main]]
name = 'cybersecurity'
pageRef = '/cybersecurity'
weight = 30

[[menus.main]]
name = 'AI'
pageRef = '/ai'
weight = 40

[[menus.main]]
name = 'philosophy'
pageRef = '/philosophy'
weight = 50

[[menus.main]]
name = 'puzzles'
pageRef = '/puzzles'
weight = 60

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
